server:
  port: 8090
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/demo1
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  output:
    ansi:
      enabled: always
  security:
    user:
      name: user
      password: 1234
logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE